env:
  commonjs: true
  es6: true
  node: true
  jest: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  semi: off
  line-break-style: off
  linebreak-style: off
  no-use-before-define: off
  import/prefer-default-export: off
  comma-dangle: off
  no-console: off
  import/no-extraneous-dependencies: off