const { config } = require('dotenv');
const { resolve } = require('path');

module.exports = {
  testEnvironment: 'node',
  roots: ['../__tests__/'],
  testMatch: ['**/*.(e2e).js'],
  testTimeout: 60000 * 7, // 7 minutes timeout
  // Enable this if you're using aws-testing-library
  setupFilesAfterEnv: ['../node_modules/aws-testing-library/lib/jest/index.js'],
}

// Load environment variables generated by serverless-export-env plugin
config({
  path: resolve(__dirname, '../.awsenv'),
  bail: 1
})
