const { config } = require('dotenv');
const { resolve } = require('path');

module.exports = {
  testEnvironment: 'node',
  roots: ['../__tests__/'],
  testMatch: ['**/*.(int|integration).js'],
  testTimeout: 60000 * 2, // 2 minutes timeout
}

// Load environment variables generated by serverless-export-env plugin
config({
  path: resolve(__dirname, '../.awsenv'),
  bail: 1,
  testEnvironment: 'node'
})
